eureka:
  client:
    # 从eureka拉取注册信息的频率，默认30
    registry-fetch-interval-seconds: 10
    # 如果是集群环境，client去获取eureka集群的node列表的频率
    # 默认值： 5 * MINUTES
    eureka-service-url-poll-interval-seconds: 60
    serviceUrl:
      # 单机配置
      #defaultZone: http://eureka:1234@localhost:8000/eureka/
      # 集群配置
      # 可以只配置集群中部分eureka即可， eureka集群之间会进行同步
      defaultZone: http://eureka:1234@localhost:8001/eureka/,http://eureka:1234@localhost:8002/eureka/
  instance:
    # 多久没收到心跳可以认为是down了，默认是90，即默认3次心跳检测失败后
    lease-expiration-duration-in-seconds: 12
    # 心跳频率， 默认30
    lease-renewal-interval-in-seconds: 10
    # 注册IP
    prefer-ip-address: true
server:
  port: 8100
spring:
  mvc:
    servlet:
      #spring mvc servlet disable lazy loading
      load-on-startup: 1
  profiles:    active:    - local
  application:
    name: gateway-eureka-base
  cloud:
    gateway:
      globalcors:        cors-configurations:          '[/**]': 
            # 允许携带认证信息
            # 允许跨域的源(网站域名/ip)，设置*为全部
            # 允许跨域请求里的head字段，设置*为全部
            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
            # 跨域允许的有效期
            allow-credentials: true            allowed-origins: 
            - "http://localhost:13009"
            - "http://localhost:13010"
            allowed-headers: "*"
            allowed-methods: 
            - OPTIONS
            - GET
            - POST
            max-age: 3600
            # 允许response的head信息
            # 默认仅允许如下6个：
            #     Cache-Control
            #     Content-Language
            #     Content-Type
            #     Expires
            #     Last-Modified
            #     Pragma
            #exposed-headers:
      routes:
      - id: producer-eureka-base
        uri: lb://producer-eureka-base
        predicates:
        - Path=/api/**
        filters:
        - StripPrefix=1
okhttp:
  connect-timeout-ms: 500
  keep-alive-duration-sec: 5000
  max-idle: 100
  read-timeout-ms: 500
  write-timeout-ms: 500
  
ribbon:
  okhttp:
    enabled: true  # ribbon lazy loading disable
  eager-load:
    enabled: true